version: "3.7"
services:
  db:
    build: ./sql
    image: persistent-db:latest
    volumes:
        - "./sql/test_db:/var/lib/mysql:Z"
    networks:
        - internal
  ss13:
    build:
      context: .
      target: ss13
    image: persistent:latest
    depends_on:
        - db
    ports:
        - "1337:1337"
    networks:
        - internal
    volumes:
        - "./config:/persistent/config"
        - "./data:/persistent/data"
networks:
    internal:

